# Generated by Django 5.1 on 2024-08-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_alter_coursedata_cid_alter_coursedata_crname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photodata',
            fields=[
                ('photo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='accountantdata',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='photo',
        ),
    ]
