# Generated by Django 5.1 on 2024-08-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_photodata_remove_accountantdata_photo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photodata',
        ),
    ]
