# Generated by Django 5.1 on 2024-08-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_delete_photodata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photodata',
            fields=[
                ('photo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
