# Generated by Django 5.1 on 2024-10-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_photodata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accountantdata',
        ),
        migrations.DeleteModel(
            name='Admindata',
        ),
        migrations.DeleteModel(
            name='Coursedata',
        ),
        migrations.DeleteModel(
            name='Installmentdata',
        ),
        migrations.DeleteModel(
            name='Logindata',
        ),
        migrations.DeleteModel(
            name='Photodata',
        ),
        migrations.DeleteModel(
            name='StudentCoursedata',
        ),
        migrations.DeleteModel(
            name='Studentdata',
        ),
    ]
