# Generated by Django 5.1 on 2024-10-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedata',
            name='remark',
            field=models.CharField(max_length=100000),
        ),
    ]
